spring:
  application:
    name: smart-job-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_job_tracker
    username: ${DB_USERNAME:sjt}
    password: ${DB_PASSWORD:sjt_dev_pwd}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082